[shooter]
turretPosition.p = 0.022
turretPosition.i = 0.005
turretPosition.d = 0.001

turretVelocity.p = 0.5
turretVelocity.i = 0.002
turretVelocity.d = 0.20
turretVelocity.f = 0.85

shooterVelocity.p = 0.0007
shooterVelocity.i = 0.0
shooterVelocity.d = 0.01
shooterVelocity.f = 0.0002

shootingSpeed.a = 4500
shootingSpeed.b = 0

[intake]
speed.load  = 0.725
speed.shoot = 0.75

[controlPanel]
extraDegrees = 90.0 # degrees to rotate past 3 rotations
p = 0.1

[drivetrain]
kinematics.ks = 0.135
kinematics.kv = 2.82
kinematics.ka = 0.73
kinematics.kw = 0.9167
